const mockNews = [
    {
      id: 1,
      title: `CDC changes school guidance, allowing desks to be closer`,
      author: `associated-press`,
      date: `2021-03-19T15:02:52.000Z`,
      url: `https://www.boston.com/news/2017-presidents-day-auto-sales/2021/03/19/cdc-changes-school-guidance-allowing-desks-to-be-closer`,
      isRead: false,
    },
    {
      id: 2,
      title: `Charlie Jane Anders: How Can Science Fiction Allow Us To Imagine Better Futures?`,
      author: `NPR/TED Staff`,
      date: `2021-03-19T13:26:00.000Z`,
      url: `https://www.npr.org/2021/03/19/978819544/charlie-jane-anders-how-can-science-fiction-allow-us-to-imagine-better-futures`,
      isRead: false,
    },
    {
      id: 3,
      title: `Brawny Domino dual-mode trailer swallows campers with yawning jaws`,
      author: `C.C. Weiss`,
      date: `2021-03-18T08:36:02.000Z`,
      url: `https://newatlas.com/outdoors/offline-domino-camper-trailer/`,
      isRead: false,
    },
    {
      id: 4,
      title: `Tropical island getaways to provide sustainable heat to Helsinki`,
      author: `Adam Williams`,
      date: `2021-03-18T14:53:41.000Z`,
      url: `https://newatlas.com/architecture/carlo-ratti-associati-hot-heart-helsinki/`,
      isRead: false,
    },
    {
      id: 5,
      title: `Urban Delivery electric van to go into production in late 2021`,
      author: `Paul Ridden`,
      date: `2021-03-18T15:46:57.000Z`,
      url: `https://newatlas.com/automotive/electric-last-mile-urban-delivery/`,
      isRead: false,
    },
    {
      id: 6,
      title: `Growing heart valve implant would never have to be replaced`,
      author: `Ben Coxworth`,
      date: `2021-03-18T17:01:28.000Z`,
      url: `https://newatlas.com/medical/growing-heart-valve-implant-children/`,
      isRead: false,
    },
    {
      id: 7,
      title: `Security keypad designed to thwart thieves – by being transparent`,
      author: `Ben Coxworth`,
      date: `2021-03-18T19:22:04.000Z`,
      url: `https://newatlas.com/good-thinking/transparent-security-keypad/`,
      isRead: false,
    },
    {
      id: 8,
      title: `Sony reveals PlayStation 5 VR controllers`,
      author: `Michael Irving`,
      date: `2021-03-19T01:18:44.000Z`,
      url: `https://newatlas.com/games/sony-playstation-5-vr-controllers/`,
      isRead: false,
    },
    {
      id: 9,
      title: `NASA\`s SLS rocket engine completes successful hot-fire test`,
      author: `David Szondy`,
      date: `2021-03-19T01:43:32.000Z`,
      url: `https://newatlas.com/space/nasas-sls-rocket-engine-completes-successful-hot-fire-test/`,
      isRead: false,
    },
    {
      id: 10,
      title: `The timeless magic of treehouses`,
      author: `New Atlas`,
      date: `2021-03-19T01:48:06.000Z`,
      url: `https://flipboard.com/@newatlas/the-timeless-magic-of-treehouses-4hkkk0apvjcc2c4g`,
      isRead: false,
    },
    {
      id: 11,
      title: `11-seat Hyundai Staria brings cosmic style to the minivan market`,
      author: `C.C. Weiss`,
      date: `2021-03-19T01:59:15.000Z`,
      url: `https://newatlas.com/automotive/11-seat-hyundai-staria-brings-cosmic-style-to-the-minivan-market/`,
      isRead: true,
    },
    {
      id: 12,
      title: `Skyfront claims multirotor endurance world record with gas-electric drone`,
      author: `Darren Quick`,
      date: `2021-03-19T02:16:37.000Z`,
      url: `https://newatlas.com/drones/skyfront-endurance-world-record-gas-electric-multirotor-drone/`,
      isRead: false,
    },
    {
      id: 13,
      title: `Unbalanced cell division offers a new target for treating baldness`,
      author: `Nick Lavars`,
      date: `2021-03-19T02:39:11.000Z`,
      url: `https://newatlas.com/medical/aberrant-cell-division-hair-loss-bald/`,
      isRead: false,
    },
    {
      id: 14,
      title: `Seaweed supplements cut cattle methane emissions by up to 82%`,
      author: `Michael Irving`,
      date: `2021-03-19T07:03:44.000Z`,
      url: `https://newatlas.com/environment/seaweed-livestock-methane-emissions-reduction/`,
      isRead: false,
    },
    {
      id: 15,
      title: `Mile-long  ship tunnel will offer safe passage through hazardous peninsula`,
      author: `Adam Williams`,
      date: `2021-03-19T11:47:55.000Z`,
      url: `https://newatlas.com/architecture/stad-ship-tunnel-approved/`,
      isRead: true,
    },
    {
      id: 16,
      title: `Prehistoric eagle shark combined traits of sharks and rays`,
      author: `Ben Coxworth`,
      date: `2021-03-19T16:36:07.000Z`,
      url: `https://newatlas.com/biology/prehistoric-eagle-shark-ray/`,
      isRead: false,
    },
    {
      id: 17,
      title: `Conductive hydrogel could find use in soft robotics and more`,
      author: `Ben Coxworth`,
      date: `2021-03-19T19:02:36.000Z`,
      url: `https://newatlas.com/materials/electrically-conductive-hydrogel/`,
      isRead: false,
    },
    {
      id: 18,
      title: `Ultralight Watt Porsche 356-inspired electric coupe transcends time`,
      author: `C.C. Weiss`,
      date: `2021-03-19T20:24:19.000Z`,
      url: `https://newatlas.com/automotive/watt-porsche-356-inspired-electric-coupe/`,
      isRead: false,
    },
    {
      id: 19,
      title: `Singapore stocks track regional gains following Fed meeting; STI up 0.9%`,
      author: `Raphael Lim`,
      date: `2021-03-18T09:48:25.000Z`,
      url: `https://www.businesstimes.com.sg/stocks/singapore-stocks-track-regional-gains-following-fed-meeting-sti-up-09`,
      isRead: false,
    },
    {
      id: 20,
      title: `Stocks to watch: Mapletree Logistics Trust, GL, Jardine Strategic, Yanlord, Matex`,
      author: `Ong Sing Yee`,
      date: `2021-03-19T00:33:34.000Z`,
      url: `https://www.businesstimes.com.sg/stocks/stocks-to-watch-mapletree-logistics-trust-gl-jardine-strategic-yanlord-matex`,
      isRead: true,
    },
    {
      id: 21,
      title: `Singapore stocks slide at Friday\`s open; STI down 0.1%`,
      author: `S Priyashini`,
      date: `2021-03-19T01:38:49.000Z`,
      url: `https://www.businesstimes.com.sg/stocks/singapore-stocks-slide-at-fridays-open-sti-down-01`,
      isRead: false,
    },
    {
      id: 22,
      title: `Asian markets tumble amid rising yields; STI down 0.1 %`,
      author: `Raphael Lim`,
      date: `2021-03-19T10:05:05.000Z`,
      url: `https://www.businesstimes.com.sg/stocks/asian-markets-tumble-amid-rising-yields-sti-down-01`,
      isRead: false,
    },
    {
      id: 23,
      title: `The suspect wanted to curb his sexual urges, a former roommate says.`,
      author: `Nicholas Bogel-Burroughs and Jack Healy`,
      date: `2021-03-19T09:01:23.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/the-suspect-wanted-to-curb-his-sexual-urges-a-former-roommate-says.html`,
      isRead: false,
    },
    {
      id: 24,
      title: `Joe Biden and Kamala Harris are set to meet with Asian-American leaders in Atlanta.`,
      author: `Neil Vigdor`,
      date: `2021-03-19T20:31:36.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/biden-harris-atlanta.html`,
      isRead: false,
    },
    {
      id: 25,
      title: `The police made prostitution arrests at one of the spas in the attacks several years ago.`,
      author: `Frances Robles`,
      date: `2021-03-19T19:22:03.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/atlanta-spas-prostitution-arrests.html`,
      isRead: false,
    },
    {
      id: 26,
      title: `White House Easter Egg Roll is canceled again because of the pandemic.`,
      author: `Katie Rogers`,
      date: `2021-03-19T20:15:02.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/white-house-easter-egg-roll-canceled.html`,
      isRead: true,
    },
    {
      id: 27,
      title: `A DeVos System Allowed 12 Minutes to Decide Student Loan Forgiveness`,
      author: `Stacy Cowley`,
      date: `2021-03-19T19:56:26.000Z`,
      url: `https://www.nytimes.com/2021/03/19/business/student-loan-forgiveness-betsy-devos.html`,
      isRead: false,
    },
    {
      id: 28,
      title: `Dennis Mileti, Expert on Preparing for Disasters, Dies at 75`,
      author: `Neil Genzlinger`,
      date: `2021-03-19T19:29:24.000Z`,
      url: `https://www.nytimes.com/2021/03/19/obituaries/dennis-mileti-dead-coronavirus.html`,
      isRead: false,
    },
    {
      id: 29,
      title: `Stay Scattered and Avoid Police, Proud Boys Were Told Before Capitol Riot`,
      author: `Alan Feuer`,
      date: `2021-03-19T20:13:48.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/politics/proud-boys-indictment.html`,
      isRead: false,
    },
    {
      id: 30,
      title: `How a Sham Candidate Helped Flip a Florida Election`,
      author: `Patricia Mazzei`,
      date: `2021-03-19T20:38:09.000Z`,
      url: `https://www.nytimes.com/2021/03/19/us/florida-senate-race-fraud.html`,
      isRead: false,
    }
]

const getMockNews = () => {
    return new Promise((onSuccess) => {
        setTimeout(() => {
            onSuccess(mockNews)
        }, 1000)
    })
}

export default getMockNews
